home/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path(_('about/'), views.about_us, name='about-us'),
    path(_('contact/'), views.contact_us, name='contact-us'),
    path(_('search/'), views.search, name='search'),
    path(_('search_auto/'), views.search_auto, name='search-auto'),
    path('comment/<int:id>/', views.add_comment, name='add-comment'),
    path('category/<int:id>/<slug:slug>/', views.category_product, name='category-product'),
    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product-detail'),
    path('faq/', views.faq, name='faq'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from home import views

urlpatterns = [
    path('selectlanguage', views.selectlanguage, name='selectlanguage'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('savelangcur', views.savelangcur, name='savelangcur'),
    path('i18n/', include('django.conf.urls.i18n')),
]



urlpatterns += i18n_patterns (
    path('currencies/', include('currencies.urls')),
    path('', include('home.urls', namespace='home')),
    path(_('product/'), include('product.urls', namespace='product')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('user/'), include('user.urls', namespace='user')),
    path(_('admin/'), admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = "order"
urlpatterns = [
    path('', views.index, name='index'),
    path('order-product/', views.order_product, name='order-product'),
    path('shop-card/', views.shop_card, name='shop-card'),
    path('delete-from-card/<int:id>/', views.delete_from_card, name='delete-from-card'),
    path('add-to-shop-card/<int:id>/', views.add_to_card, name='add-to-card'),
]

user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path('', views.index, name='profile'),
    path('login/', views.login_form, name='login'),
    path('signup/', views.signup_form, name='signup'),
    path('logout/', views.logout_form, name='logout'),
    path('update/', views.user_update, name='user-update'),
    path('password/', views.user_password, name='password'),
    path('comment/', views.user_comment, name='user-comment'),
    path('comment/delete/<int:id>/', views.user_comment_delete, name='comment-delete'),
    path('order/', views.user_order, name='order'),
    path('order/detail/<int:id>/', views.user_order_detail, name='order-detail'),
    path('order/product/', views.user_order_product, name='order-product'),
    path('order/product-detail/<int:id>/<int:oid>/', views.user_order_product_detail, name='order-product-detail'),
]

home/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField



class Language(models.Model):
    name= models.CharField(max_length=20)
    code= models.CharField(max_length=5)
    status=models.BooleanField()
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

llist = Language.objects.filter(status=True)
list1 = []
for rs in llist:
    list1.append((rs.code,rs.name))
langlist = (list1)

class Settings(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False')
    )
    title = models.CharField(max_length=150)
    keyword = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=60)
    smtpserver = models.CharField(blank=True, max_length=50)
    smtpemail = models.CharField(blank=True, max_length=50)
    smtppassword = models.CharField(blank=True, max_length=20)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to="settings_images")
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    youtube = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class SettingLang(models.Model):
    setting = models.ForeignKey(Settings, on_delete=models.CASCADE)
    lang = models.CharField(max_length=8, choices=langlist)
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)

    def __str__(self):
        return self.title

class ContactMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )

    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=60)
    subject = models.CharField(blank=True, max_length=55)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=6, choices = STATUS, default="New")
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name 


class FAQ(models.Model):
    STATUS = (
        ('True','True'),
        ('False','False'),
    )
    lang = models.CharField(max_length=8, choices = langlist, blank=True, null=True)
    ordernumber = models.IntegerField()
    question    = models.CharField(max_length=200)
    answer      = RichTextUploadingField()
    status      = models.CharField(max_length=5, choices=STATUS)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from . models import ContactMessage

class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactMessage
        fields = ['name','email','subject','message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Name & surename'}),
            'subject': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': forms.Textarea(attrs={'class': 'input', 'placeholder': 'your message', 'roww': '5'})
        }


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    catid = forms.IntegerField()

    

home/views.py
import json 
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import translation
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.conf import settings

from . models import Settings, ContactMessage, FAQ, SettingLang, Language
from . forms import ContactForm, SearchForm
from product.models import Category, CategoryLang, Comment, Images, Product, Variants
from product.forms import CommentForm
from user.models import Profile


def selectlanguage(request):
    if request.method == 'POST':  # check post
        cur_language = translation.get_language()
        lasturl= request.META.get('HTTP_REFERER')
        lang = request.POST['language']
        translation.activate(lang)
        request.session[translation.LANGUAGE_SESSION_KEY]=lang
        #return HttpResponse(lang)
        return HttpResponseRedirect(lang)

def index(request):
    # check currency, set currency 
    if not request.session.has_key('currency'):
        request.session['currency'] = settings.DEFAULT_CURRENCY

    setting = Settings.objects.get(pk=1)
    # category = Category.objects.all()
    products_latest = Product.objects.all().order_by('-id')[:4] # latest
    # >>>>>>>>>>>>>>>> M U L T I   L A N G U G A E >>>>>> START
    defaultlang = settings.LANGUAGE_CODE[0:2]
    currentlang = request.LANGUAGE_CODE[0:2]

    if defaultlang != currentlang:
        setting = SettingLang.objects.get(lang=currentlang)
        products_latest = Product.objects.raw(
            'SELECT p.id,p.price, l.title, l.description,l.slug  '
            'FROM product_product as p '
            'LEFT JOIN product_productlang as l '
            'ON p.id = l.product_id '
            'WHERE  l.lang=%s ORDER BY p.id DESC LIMIT 4', [currentlang])

    products_slider = Product.objects.all().order_by('id')[:4] #first 4 product 
    products_picked = Product.objects.all().order_by('?')[:4] # random 
    page = "index"
    context = {
        'setting': setting,
        'page': page,
        # 'category': category,
        'products_slider': products_slider,
        'products_latest': products_latest,
        'products_picked': products_picked,
    }
    return render(request,'index.html',context)

def about_us(request):
    # category = Category.objects.all()
    defaultlang = settings.LANGUAGE_CODE[0:2]
    currentlang = request.LANGUAGE_CODE[0:2]
    setting = Settings.objects.get(pk=1)
    if defaultlang != currentlang:
        setting = SettingLang.objects.get(lang=currentlang)
    context = {
        'setting': setting,
        # 'category': category
    }
    return render(request, 'about.html', context)

def contact_us(request):
    currentlang = request.LANGUAGE_CODE[0:2]
    # category = Category.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "your message has been submitted we will get you back soon ")
            return redirect('home:contact-us')
            # return HttpResponseRedirect(reverse('home:contact-us'))

    defaultlang = settings.LANGUAGE_CODE[0:2]
    currentlang = request.LANGUAGE_CODE[0:2]
    setting = Settings.objects.get(pk=1)
    if defaultlang != currentlang:
        setting = SettingLang.objects.get(lang=currentlang)
    form = ContactForm()
    context = {
        'setting': setting,
        'form': form,
        # 'category': category
    }
    return render(request, 'contact.html', context)

# this one was for before multi language implementation 
# def category_product(request, id, slug):
#     products = Product.objects.filter(category_id=id)
#     category = Category.objects.all()

#     context = {
#         'products': products,
#         'category': category
#     }
#     return render(request, "category_products.html", context)


def category_product(request,id,slug):
    # category = Category.objects.all()
    defaultlang = settings.LANGUAGE_CODE[0:2] # i get first two because it's to lang like --> en-US or fa-IR also in my table i define only 'en' or 'af'
    currentlang = request.LANGUAGE_CODE[0:2]
    catdata = Category.objects.get(pk=id)
    products = Product.objects.filter(category_id=id) #default language
    if defaultlang != currentlang:
        try:
            products = Product.objects.raw(
                'SELECT p.id,p.price,p.amount,p.image,p.variant,l.title, l.keywords, l.description,l.slug,l.detail '
                'FROM product_product as p '
                'LEFT JOIN product_productlang as l '
                'ON p.id = l.product_id '
                'WHERE p.category_id=%s and l.lang=%s', [id, currentlang])
        except:
            pass
        catdata = CategoryLang.objects.get(category_id=id, lang=currentlang)

    context={
        'products': products,
        # 'category':category,
        'catdata':catdata }
    return render(request,'category_products.html',context)


def search(request):
    if request.method == 'POST': 
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            catid = form.cleaned_data['catid']

            if catid == 0:
                products = Product.objects.filter(title__icontains=query)
            else:
                products = Product.objects.filter(title__icontains=query, category_id=catid)

            category = Category.objects.all()
            context = {
                'products': products,
                'category': category,
                'query': query
                }
            return render(request, 'search_products.html', context)
    
    return HttpResponseRedirect('/')


def search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        products = Product.objects.filter(title__icontains=q)
        results = []
        for product in products:
            product_json = {}
            # product_json = product.title + "," + product.description
            product_json = product.title 
            results.append(product_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)


def product_detail(request, id, slug):
    query = request.GET.get('q')
    # >>>>>>>>>>>>>>>> M U L T I   L A N G U G A E >>>>>> START
    defaultlang = settings.LANGUAGE_CODE[0:2] #en-EN
    currentlang = request.LANGUAGE_CODE[0:2]
    #category = categoryTree(0, '', currentlang)
    # category = Category.objects.all()
    product = Product.objects.get(pk=id)

    if defaultlang != currentlang:
        try:
            prolang =  Product.objects.raw('SELECT p.id,p.price,p.amount,p.image,p.variant,l.title, l.keywords, l.description,l.slug,l.detail '
                                            'FROM product_product as p '
                                            'INNER JOIN product_productlang as l '
                                            'ON p.id = l.product_id '
                                            'WHERE p.id=%s and l.lang=%s',[id,currentlang])
            product=prolang[0] # selecting one row because of our detail which is one
        except:
            pass
    # <<<<<<<<<< M U L T I   L A N G U G A E <<<<<<<<<<<<<<< end

    images = Images.objects.filter(product_id = id)
    comments = Comment.objects.filter(product_id = id, status=True)
    # if you don't wanna use 'averagereview or counterreview' of model so you can do in this view as follows
    # review = Comment.objects.filter(product_id=id, status=True).aggregate(Count('id'),Avg('rate'))
    # Retrieve values : review.rate__avg, review.id, status =True).aggregate(Count('id'), Avg('rate'))
    # review = Comment.objects.raw('SELECT id, count(id) as counterew, avg(rate) as avgrew From product_comment WHERE product_id=%s and STATUS = "True"',[id])[0]
    # Retrieve values: review.avgrew, review.countrew
    context = {
        'product': product,
        'images': images, 
        # 'category': category,
        'comments': comments
    }
    if product.variant != "None":
        if request.method == "POST":
            variant_id = request.POST.get('variantid')
            variant = Variants.objects.get(id=variant_id) # select product by click color radio
            colors = Variants.objects.filter(product_id=id, size_id=variant.size_id)
            sizes = Variants.objects.raw('SELECT * FROM product_variants WHERE product_id=%s GROUP BY size_id', [id])
            query += variant.title+' Size:'+str(variant.size)+' Color:' +str(variant.color)
        else:
            variants = Variants.objects.filter(product_id=id)
            colors = Variants.objects.filter(product_id=id, size_id=variants[0].size_id)
            sizes = Variants.objects.raw('SELECT * FROM product_variants WHERE product_id=%s GROUP BY size_id', [id])
            variant = Variants.objects.get(id=variants[0].id)
        context.update({
            'sizes': sizes,
            'colors': colors,
            'variant': variant,
            'query': query
        })
    return render(request, "product_detail.html", context)

def ajaxcolor(request):
    data = {}
    if request.POST.get('action')=='post':
        size_id = request.POST.get('size')
        productid= request.POST.get('productid')
        colors = Variants.objects.filter(product_id =productid, size_id=size_id)
        context = {
            'size_id': size_id,
            'productid': productid,
            'colors': colors

home/templates/header.html
{% load static %}
{% load i18n %}
{% load currency %}
<header>
    <!-- top Header -->
    <div id="top-header">
        <div class="container">
            <div class="pull-left">
                <span>{% trans "Welcome to E-shop!" %}</span>
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}" role="alert">
                            {{ message |safe }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>




            <div class="pull-right">
                <ul class="header-top-links">
                    <li><a href="#">{% trans "Store" %}</a></li>
                    <li><a href="#">{% trans "Newsletter" %}</a></li>
                    <li><a href="{% url 'home:faq' %}">{% trans "FAQ" %}</a></li>
                    <li class="dropdown default-dropdown">
                        <form action="{% url 'selectlanguage' %}" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <select name="language" onchange="submit()" >

                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                {% endfor %}

                            </select>
                            <noscript>
                                <input type="submit" value="Set" />
                            </noscript>
                        </form>
                    </li>

                    <li class="dropdown default-dropdown">


                        <form id="currency_switcher" method="POST" action="{% url 'selectcurrency' %}">
                            {% csrf_token %}
                            <select name="currency" onchange="submit()" >
                                {% for curr in CURRENCIES %}
                                    <option value="{{ curr.code }}"
                                            {% ifequal curr.code request.session.currency %}selected="selected"{% endifequal %}>
                                        {{ curr.symbol }} {{ curr.name }}
                                    </option>
                                {% endfor %}
                            </select>

                            <noscript>
                                <input type="submit" value="Set" />
                            </noscript>

                        </form>
                    </li>

                    <li class="dropdown default-dropdown">
                        <form id="currency_switcher" method="POST" action="{% url 'savelangcur' %}">
                            {% csrf_token %}
                            <input type="submit" value="Save" />
                        </form>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <!-- /top Header -->

    <!-- header -->
    <div id="header">
        <div class="container">
            <div class="pull-left">
                <!-- Logo -->
                <div class="header-logo">
                    <a class="logo" href="{% url 'home:index' %}">
                        <img src="{% static '' %}img/logo.png" alt="">
                    </a>
                </div>
                <!-- /Logo -->
                <script>
                    $(function() {
                        $("#query").autocomplete({
                            source: "{% url 'home:search-auto' %}",
                            select: function (event, ui) { //item selected
                                AutoCompleteSelectHandler(event, ui)
                            },
                            minLength: 2,
                        });
                    });
                    function AutoCompleteSelectHandler(event, ui)
                    {
                        var selectedObj = ui.item;
                    }
                </script>

                <!-- Search -->
                <div class="header-search">
                    <form action="{% url 'home:search' %}" method="post">
                        {% csrf_token %}
                        <input id="query" name="query" class="input search-input" type="text" placeholder="Enter your keyword">
                        <select name="catid"  class="input search-categories">
                            <option value="0">{% trans "All Categories" %}</option>
                            {% comment %}
                                {% load mptt_tags %}

                                {% recursetree category %}
                                    {% if node.is_leaf_node %}
                                        <option value="{{ node.id }}">{{ node.title }}</option>
                                    {% endif %}
                                    {% if not node.is_leaf_node %}
                                        <optgroup label="{{ node.title }}">
                                            {{ children }}
                                        </optgroup>
                                    {% endif %}
                                {% endrecursetree %}
                            {% endcomment %}
                                
                        </select>
                        <button class="search-btn"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <!-- /Search -->

            </div>
            <div class="pull-right" >
                <ul class="header-btns">
                    <!-- Account -->
                    <li class="header-account dropdown default-dropdown">
                        {% if user.id is not None %}
                            <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                                <div class="header-btns-icon">
                                    <img src="{{ request.session.userimage }}" style="height: 40px; border-radius: 30%">
                                </div>
                                <strong class="text-uppercase">{{ user.first_name }} <i class="fa fa-caret-down"></i></strong>
                            </div>
                        {% else %}
                            <a href="{% url 'user:login' %}" class="text-uppercase">Login</a> / <a href="{% url 'user:signup' %}" class="text-uppercase">Sign Up</a>
                        {% endif %}

                        <ul class="custom-menu">
                            <li><a href="{% url 'user:profile' %}"><i class="fa fa-user-o"></i> {% trans "My Account" %}</a></li>
                            <li><a href="#"><i class="fa fa-heart-o"></i> {% trans "My Favorits" %}</a></li>
                            <li><a href="{% url 'user:order' %}"><i class="fa fa-exchange"></i> {% trans "My Orders " %}</a></li>
                            <li><a href="{% url 'user:user-comment' %}"><i class="fa fa-check"></i> {% trans "My Comments" %}</a></li>
                            <li><a href="{% url 'user:logout' %}"><i class="fa fa-unlock-alt"></i> {% trans "Logout" %}</a></li>

                        </ul>
                    </li>
                    <!-- /Account -->

                    <!-- Cart -->
                    <li class="header-cart dropdown default-dropdown">
                        <a href="{% url 'order:shop-card'%}" >
                            <div class="header-btns-icon">
                                <i class="fa fa-shopping-cart"></i>
                                {% load myapptags %}
                                {% shopcardcount user.id as count %}

                                <span class="qty">{{ count }}</span>
                            </div>
                            <strong class="text-uppercase">{% trans "My Cart:" %}</strong>
                            <br>

                        </a>

                    </li>
                    <!-- /Cart -->

                    <!-- Mobile nav toggle-->
                    <li class="nav-toggle">
                        <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                    </li>
                    <!-- / Mobile nav toggle -->
                </ul>
            </div>
        </div>
        <!-- header -->
    </div>
    <!-- container -->
</header>
<!-- /HEADER -->

home/templates/index.html
{% extends 'homebase.html' %}

{% block title %} {{setting.title}} {% endblock %}
{% block description %} {{setting.description}} {% endblock %}
{% block keywords %} {{setting.keyword}} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block slider %} {% include 'slider.html' %} {% endblock %}
{% block body %} {% include 'content.html' %} {% endblock %}

home/templates/sidebar.html
{% load static %}
{% load i18n %}

<!-- NAVIGATION -->
<div id="navigation">
    <!-- container -->
    <div class="container">
        <div id="responsive-nav">
            <!-- category nav -->
            {% if page %}
                <div class="category-nav">
            {% else %}
                <div class="category-nav show-on-click">
            {% endif %}

            <span class="category-header">{% trans "Categories" %} <i class="fa fa-list"></i></span>


            {% load myapptags %}
            {% if LANGUAGE_CODE is None %}
                {% get_current_language as LANGUAGE_CODE %}
                {% categoryTree 0 '' LANGUAGE_CODE as category %}
            {% else %}
                {% categoryTree 0 '' 'en' as category %}
            {% endif %}


            <ul class="category-list">
                {{ category | safe  }}
            </ul>
            </div>
            <!-- /category nav -->
            <!-- menu nav -->
            <div class="menu-nav">
                <span class="menu-header">Menu <i class="fa fa-bars"></i></span>
                <ul class="menu-list">
                    <li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
                    <li><a href="{% url 'home:about-us' %}">{% trans "About Us" %}</a></li>
                    <li><a href="{% url 'home:contact-us' %}">{% trans "Contact Us" %}</a></li>
                </ul>
            </div>
            <!-- menu nav -->
            </div>
        </div>
        <!-- /container -->
    </div>
    <!-- /NAVIGATION -->

home/templates/sidebar2.html
{% load static %}
{% load i18n %}
<!-- load my app tag custom template tag -->
<!-- here we assigned to category because to match our category tree objects -->

	<!-- NAVIGATION -->
	<div id="navigation">
		<!-- container -->
		<div class="container">
			<div id="responsive-nav">
				<!-- category nav -->
				<!-- here we need this because our index is not the same as about us or contact us
					you can implement in two ways which like as follows
				-->
				{% if page %}
					<div class="category-nav">
				{% else %}
					<div class="category-nav show-on-click">
				{% endif %}

				<!-- {% if request.resolver_match.url_name == 'home:index' %}
					<div class="category-nav">
				{% else %}
					<div class="category-nav show-on-click">
				{% endif %} -->
					<span class="category-header">{% trans "Categories" %} <i class="fa fa-list"></i></span>
					<!-- {% load myapptags %}
					{% categorylist as category %} -->
					{% load mptt_tags %}
					<ul class="category-list">
						{% recursetree category %}
							<li class="dropdown side-dropdown">
								<a href="{% url 'home:category-product' node.id node.slug %}" class="dropdown-toggle" {% if not node.is_leaf_node %} data-toggle="dropdown" aria-expanded="true" {% endif %} >
									{{ node.title }} {% if not node.is_leaf_node %} <i class="fa fa-angle-right"> {% endif %}</i>
								</a>
								<div class="custom-menu">
									<div class="row">
										<div class="col-md-4">
											{% if not node.is_leaf_node %}
												<ul class="list-links">
													<li>
														<!-- <h3 class="list-links-title">Sub Categories</h3></li> -->
														<hr>
													<li><a href="#">{{ children }}</a></li>
												</ul>
											{% endif %}
											<hr class="hidden-md hidden-lg">
										</div>
									</div>
									<!-- <div class="row hidden-sm hidden-xs">
										<div class="col-md-12">
											<hr>
											<a class="banner banner-1" href="#">
											<img src="{{ node.image.url }}" style="{ width: 50%; height: 100px;}" alt="">
												<div class="banner-caption text-center">
													<h2 class="white-color">NEW COLLECTION</h2>
													<h3 class="white-color font-weak">HOT DEAL</h3>
												</div>
											</a>
										</div>
									</div> -->
								</div>
							</li>
						{% endrecursetree %}
					</ul>
				</div>
				<!-- /category nav -->

				<!-- menu nav -->
				<div class="menu-nav">
					<span class="menu-header">{% trans "Menu" %} <i class="fa fa-bars"></i></span>
					<ul class="menu-list">
						<li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
						<li><a href="{% url 'home:about-us' %}">{% trans "About us" %}</a></li>
						<li><a href="{% url 'home:contact-us' %}">{% trans "Contact" %}</a></li>
					</ul>
				</div>
				<!-- menu nav -->
			</div>
		</div>
		<!-- /container -->
	</div>
	<!-- /NAVIGATION -->