home/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path(_('about/'), views.about_us, name='about-us'),
    path(_('contact/'), views.contact_us, name='contact-us'),
    path(_('search/'), views.search, name='search'),
    path(_('search_auto/'), views.search_auto, name='search-auto'),
    path('comment/<int:id>/', views.add_comment, name='add-comment'),
    path('category/<int:id>/<slug:slug>/', views.category_product, name='category-product'),
    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product-detail'),
    path('faq/', views.faq, name='faq'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from home import views

urlpatterns = [
    path('selectlanguage', views.selectlanguage, name='selectlanguage'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('savelangcur', views.savelangcur, name='savelangcur'),
    path('i18n/', include('django.conf.urls.i18n')),
]



urlpatterns += i18n_patterns (
    path('currencies/', include('currencies.urls')),
    path('', include('home.urls', namespace='home')),
    path(_('product/'), include('product.urls', namespace='product')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('user/'), include('user.urls', namespace='user')),
    path(_('admin/'), admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path('', views.index, name='profile'),
    path('login/', views.login_form, name='login'),
    path('signup/', views.signup_form, name='signup'),
    path('logout/', views.logout_form, name='logout'),
    path('update/', views.user_update, name='user-update'),
    path('password/', views.user_password, name='password'),
    path('comment/', views.user_comment, name='user-comment'),
    path('comment/delete/<int:id>/', views.user_comment_delete, name='comment-delete'),
    path('order/', views.user_order, name='order'),
    path('order/detail/<int:id>/', views.user_order_detail, name='order-detail'),
    path('order/product/', views.user_order_product, name='order-product'),
    path('order/product-detail/<int:id>/<int:oid>/', views.user_order_product_detail, name='order-product-detail'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

from currencies.models import Currency

from home.models import Language


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=15)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to = "profile_image")
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True, blank=True)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name+' ' + self.user.last_name + ' [ ' + self.user.username + ']'
    
    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = "Image"

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import EmailInput, FileInput, Select, TextInput
from .models import Profile

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True, label='User Name')
    email = forms.EmailField(max_length=60, required=True, label="Email")
    first_name = forms.CharField(max_length= 50, required=False, label="First Name")
    last_name = forms.CharField(max_length=50, required=False, label="Last Name")

    class Meta:
        model = User 
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')


class UserUpdateForm(UserChangeForm):
    
    class Meta:
        model = User 
        fields = ('username','email', 'first_name', 'last_name')
        widgets = {
            'username':     TextInput(attrs={'class': 'input', 'placeholder':'put your username'}),
            'email':        EmailInput(attrs={'class': 'input', 'placeholder': 'put your Email'}),
            'first_name':   TextInput(attrs={'class': 'input', 'placeholder': 'put your first Name'}),
            'last_name':    TextInput(attrs={'class': 'input', 'placeholder': 'put your Last Name'})
        }


CITY = [
    ('Kabul','Kabul'),
    ('Daykundi','Daykundi'),
    ('Mazar','Mazar'),
    ('Herat','Herat'),
    ('Qandahar','Qandahar'),
]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ('phone','address','city','country','image', 'language')
        widgets = {
            'phone':    TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address':  TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'country':  TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'city':     Select(attrs={'class': 'input', 'placeholder': 'City'}, choices=CITY),
            'image':    FileInput(attrs={'class': 'input', 'placeholder': 'Image'})
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse

from product.models import Category, Comment
from order.models import Order, OrderProduct 
from .models import Profile
from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm


@login_required
def index(request):
    # if you want to don't repeat Category in your functions so use custom template tags
    categoy = Category.objects.all()
    profile = Profile.objects.get(user_id = request.user.id)
    context = {
        'category': categoy,
        'profile': profile
    }
    return render(request, "user_profile.html", context)

def login_form(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            profile = Profile.objects.get(user_id = request.user.id)
            request.session['userimage'] = profile.image.url
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('home:index'))
        else:
            # Return an 'invalid login' error message.
            messages.warning(request, "your username or password is in correct plz try again")
            return HttpResponseRedirect(reverse('user:login'))

    category = Category.objects.all()

    context = {
        'category': category
    }
    return render(request, "login.html", context)

def signup_form(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save() # signUp completed here but now i'm gonna login at the same time
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            # then I need to create a Profile for user as well--> one way is with signal and 
            # another way is as follows 
            data = Profile()
            data.user_id = request.user.id 
            data.image = "profile_image/avatar.png"
            data.save()
            messages.success(request, "your profile has been created successfully")
            return HttpResponseRedirect(reverse("home:index"))
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect(reverse("user:signup"))
    form = SignUpForm()
    category = Category.objects.all()

    context = {
        'category': category, 
        'form': form
    }
    return render(request, "signup.html", context)

def logout_form(request):
    logout(request)
    return HttpResponseRedirect(reverse("home:index"))

@login_required
def user_update(request):
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=request.user) # request user is user data
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "your account has been updated")
            return HttpResponseRedirect(reverse("user:profile"))
    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, "user_update.html", context)

@login_required
def user_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "your password has been changed successfully")
            return HttpResponseRedirect(reverse("user:profile"))
        else:
            messages.error(request, "Please correct the error below.<br>"+str(form.errors))
            return HttpResponseRedirect(reverse("user:password"))
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        context = {
            'category': category,
            'form': form
        }
        return render(request, "user_password.html", context)

@login_required
def user_order(request):
    category = Category.objects.all()
    orders = Order.objects.filter(user_id = request.user.id)

    context = {
        'category': category,
        'orders': orders
    }
    return render(request, "user_orders.html", context)

@login_required
def user_order_detail(request, id):
    category = Category.objects.all()
    # why i'm using user_id ---> it's because of security it means that no buddy can access except user
    order = Order.objects.get(user_id = request.user.id, id=id)
    orderitems = OrderProduct.objects.filter(order_id = id)
    context = {
        'order': order,
        'orderitems': orderitems,
        'category': category
    }
    return render(request, "user_order_detail.html", context)
    
@login_required
def user_order_product(request):
    category = Category.objects.all()
    order_product = OrderProduct.objects.filter(user_id = request.user.id)
    context = {
        'category': category,
        'order_product': order_product
    }
    return render(request, "order_products.html", context)

@login_required
def user_order_product_detail(request, id, oid):
    category = Category.objects.all()
    order = Order.objects.get(user_id = request.user.id, id=oid)
    orderitems = OrderProduct.objects.filter(id=id, user_id=request.user.id)
    context = {
        'category': category,
        'order': order,
        'orderitems': orderitems
    }
    return render(request, "user_order_detail.html", context)

@login_required
def user_comment(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id = current_user.id)
    context = {
        'category': category,
        'comments': comments
    }
    return render(request, "user_comment.html", context)

@login_required
def user_comment_delete(request, id):
    Comment.objects.filter(id=id, user_id=request.user.id).delete()
    messages.success(request, "Your comment has been deleted successfully!")
    return HttpResponseRedirect(reverse('user:user-comment'))
    

user/templates/login.html
{% extends 'homebase.html' %}
{% load i18n %}
{% block title %} User Login  {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'home:index' %}">{% trans "Home" %}</a></li>
				<li class="active">{% trans "User Login" %}</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

                <div class="col-md-12">
                    <div class="billing-details">

                        <div class="section-title">
                            <h3 class="title">{% trans "Login Form" %}</h3>
                        </div>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
								<input class="input" type="text" name="username" placeholder="Fuser Name">
							</div>
							<div class="form-group">
								<input class="input" type="password" name="password" placeholder="Password">
							</div>
                            <input type="submit" class="btn btn-primary" value="Login">
                        </form>

                    </div>
                </div>


			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

{% endblock %}

user/templates/order_products.html
{% extends 'homebase.html' %}

{% block title %} Order Detail {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Produts</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-2">
                    {% include "user_panel.html" %}
                </div>

                <div class="col-md-10">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Product List</h3>
                        </div>

                        <table class="shopping-cart-table table">
                            <tr>
                                <th class="text-left">Id </th>
                                <th class="text-left">Product Name </th>
                                <th class="text-left">Price </th>
                                <th class="text-left">Qauatity </th>
                                <th class="text-left">Amount </th>
                                <th class="text-left">Status </th>
                                <th class="text-left">Date </th>
                                <th class="text-left">Detail </th>
                            </tr>
                            {% for rs in order_product %}
                                <tr>
                                    <td class="text-left">
                                        <a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">
                                            {% if rs.variant.image_id > 0 %}
                                                <img src="{{rs.variant.image }}" alt="" style="height: 80px">
                                            {% else %}
                                                <img src="{{rs.product.image.url}}" alt="" style="height: 80px">
                                            {% endif %}
                                        </a>
                                    </td>
                                    <td>{{ rs.product.title}} {{ rs.variant.size }}   {{ rs.variant.color }}</td>
                                    <td class="text-left">{{ rs.price}} </td>
                                    <td class="text-left">{{ rs.quantity}} </td>
                                    <td class="text-left">{{ rs.amount}} </td>
                                    <td class="text-left">{{ rs.status}} </td>
                                    <td class="text-left">{{ rs.created_at}} </td>
                                    <td class="text-left"><a class="primary-btn" href="{% url 'user:order-product-detail' rs.id rs.order.id %}"> Detail </a></td>

                                </tr>
                            {% endfor %}

                        </table>

                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

user/templates/signup.html
{% extends 'homebase.html' %}

{% block title %} User Sign Up  {{ setting.title }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">Home</a></li>
				<li class="active">User Sign Up </li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">

                <div class="col-md-12">
                    <div class="billing-details">

                        <div class="section-title">
                            <h3 class="title">Sign Up Form</h3>
                        </div>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{message.tags}}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}

                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }}<br>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                </p>
                            {% endfor %}
                            <button type="submit">Sign up</button>
                        </form>
                    </div>
                </div>


			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

{% endblock %}

user/templates/user_comment.html
{% extends 'homebase.html' %}

{% block title %} User comment {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">User comment</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-2">
                    {% include "user_panel.html" %}
                </div>

                <div class="col-md-10">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">User Comment</h3>
                        </div>

                        <table class="shopping-cart-table table">
                            <tr>
                                <th class="text-left">Product</th>
                                <th class="text-left">Rate</th>
                                <th class="text-left">Subject</th>
                                <th class="text-left">Comment</th>
                                <th class="text-left">Status</th>
                                <th class="text-left">Date</th>
                                <th class="text-left">Detail</th>
                            </tr>
                            
                            {% for rs in comments %}
                                <tr>
                                    <td class="text-left">
                                        <a href="{% url 'home:product-detail' rs.product.id rs.product.slug %}">{{rs.product.title}}</a>
                                    </td>
                                    <td class="text-left">{{rs.rate}}</td>
                                    <td class="text-left">{{rs.subject}}</td>
                                    <td class="text-left">{{rs.comment}}</td>
                                    <td class="text-left">{{rs.status}}</td>
                                    <td class="text-left">{{rs.created_at}}</td>
                                    <td class="text-left"><a href="{% url 'user:comment-delete' rs.product.id %}" class="primary-btn" onclick="return confirm(' Will be delete Are you sure? ')">Delete</a></td>
                                    <td class="text-left"></td>
                                </tr>
                            {% endfor %}
                                
                        </table>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

user/templates/user_orders.html
{% extends 'homebase.html' %}
{% block title %} Order List {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order List</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-3"> 
                    {% include 'user_panel.html' %}
                </div>
                <div class="col-md-9">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order List</h3>
                        </div>
                        <table class="shopping-cart-table table">
                            <tr>
                                <td class="txt-left">Id</td>
                                <td class="txt-left">First Name</td>
                                <td class="txt-left">Last Name</td>
                                <td class="txt-left">Total</td>
                                <td class="txt-left">Status</td>
                                <td class="txt-left">Date</td>
                                <td class="txt-left">Detail</td>
                            </tr>
                            
                            {% for rs in orders %}
                                <tr>
                                    <td class="text-left">{{rs.id}}</td>
                                    <td class="text-left">{{rs.first_name}}</td>
                                    <td class="text-left">{{rs.last_name}}</td>
                                    <td class="text-left">{{rs.total}}</td>
                                    <td class="text-left">{{rs.status}}</td>
                                    <td class="text-left">{{rs.created_at}}</td>
                                    <td class="text-left"><a href="{% url 'user:order-detail' rs.id %}" class="primary-btn">Detail</a></td>
                                </tr>
                            {% endfor %}
                                
                        </table>
                        <div class="pull-right">
                            <a href="{% url 'order:order-product' %}" class="primary-btn">Place Order</a>
                        </div>
                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

user/templates/user_panel.html
<div class="billing-details">
    <div class="section-title">
        <h3 class="title">User Panel</h3>
    </div>
    <div class="aside">
    <ul class="list-links">
        <li><a href="{% url 'user:profile' %}">User Profile</a></li>
        <li><a href="{% url 'user:order' %}">My Orders</a></li>
        <li><a href="{% url 'user:order-product' %}">My Order Product</a></li>
        <li><a href="{% url 'user:user-comment' %}">My Comments</a></li>
        <li><a href="/user/favorits">My Favorits</a></li>
        <li><a href="/user/products">My Products</a></li>
        <li><a href="/logout">Logout</a></li>
    </ul>
</div>
</div>

user/templates/user_profile.html
{% extends 'homebase.html' %}

{% block title %}  {{ user.first_name }} Profile {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">User Profile</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->

    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-3">
                    {% include "user_panel.html" %}
                </div>

                <div class="col-md-9">
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">User Profile Inf.</h3>
                        </div>
                    </div>
                    <table class="shopping-cart-table table">
                        <tr>
                            <th class="text-left">
                                <a href="{% url 'user:user-update' %}" class="primary-btn">Update Profile</a>
                                <a href="{% url 'user:password' %}" class="primary-btn">Change Password</a>
                            </th>
                            <td><img src="{{ profile.image.url }}" style="border-radius: 45px; height: 200px "></td>
                        </tr>
                        <tr>
                            <th class="text-left">Name Surname</th>
                            <td class="text-left">{{ user.first_name}} {{ user.last_name}} </td>
                        </tr>
                        <tr>
                            <th class="text-left">Email</th>
                            <td class="text-left">{{ profile.user.email}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Phone</th>
                            <td class="text-left">{{ profile.phone}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Addres</th>
                            <td class="text-left">{{ profile.address}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">City</th>
                            <td class="text-left">{{ profile.city}}</td>
                        </tr>
                        <tr>
                            <th class="text-left">Country</th>
                            <td class="text-left">{{ profile.country}}</td>
                        </tr>

                    </table>
                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}