home/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path(_('about/'), views.about_us, name='about-us'),
    path(_('contact/'), views.contact_us, name='contact-us'),
    path(_('search/'), views.search, name='search'),
    path(_('search_auto/'), views.search_auto, name='search-auto'),
    path('comment/<int:id>/', views.add_comment, name='add-comment'),
    path('category/<int:id>/<slug:slug>/', views.category_product, name='category-product'),
    path('product-detail/<int:id>/<slug:slug>/', views.product_detail, name='product-detail'),
    path('faq/', views.faq, name='faq'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from home import views

urlpatterns = [
    path('selectlanguage', views.selectlanguage, name='selectlanguage'),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('savelangcur', views.savelangcur, name='savelangcur'),
    path('i18n/', include('django.conf.urls.i18n')),
]



urlpatterns += i18n_patterns (
    path('currencies/', include('currencies.urls')),
    path('', include('home.urls', namespace='home')),
    path(_('product/'), include('product.urls', namespace='product')),
    path(_('order/'), include('order.urls', namespace='order')),
    path(_('user/'), include('user.urls', namespace='user')),
    path(_('admin/'), admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = "order"
urlpatterns = [
    path('', views.index, name='index'),
    path('order-product/', views.order_product, name='order-product'),
    path('shop-card/', views.shop_card, name='shop-card'),
    path('delete-from-card/<int:id>/', views.delete_from_card, name='delete-from-card'),
    path('add-to-shop-card/<int:id>/', views.add_to_card, name='add-to-card'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User

from product.models import Product, Variants


class ShopCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat

    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return self.product.price 

    @property
    def amount(self):
        return (self.quantity*self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceld', 'Canceld'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    ip = models.CharField(max_length=20, blank=True)
    adminnote = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderProduct(models.Model):
    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Canceled','Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=8, choices=STATUS, default="New")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True) 

    def __str__(self):
        return self.product.title

order/forms.py
from django import forms
from .models import ShopCard, Order


class ShopCardForm(forms.ModelForm):

    class Meta:
        model = ShopCard
        fields = ['quantity']
        

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone','city', 'country']
        

order/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.crypto import get_random_string

from .models import ShopCard, Order, OrderProduct
from .forms import ShopCardForm, OrderForm
from product.models import Category, Product, Variants
from user.models import Profile

def index(request):
    return HttpResponse("order index")

@login_required
def add_to_card(request, id):
    # return HttpResponse(str(id))
    url = request.META.get('HTTP_REFERER') # get the last url 
    current_user = request.user # access to User session information 

    product= Product.objects.get(pk=id)
    if product.variant != 'None':
        variantid = request.POST.get('variantid')  # from variant add to cart
        checkinvariant = ShopCard.objects.filter(variant_id=variantid, user_id=current_user.id)  # Check product in shopcart
        if checkinvariant:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""
    else:
        checkinproduct = ShopCard.objects.filter(product_id=id, user_id=current_user.id) # Check product in shopcart
        if checkinproduct:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""

    if request.method == 'POST':  # if there is a post
        form = ShopCardForm(request.POST)
        if form.is_valid():
            if control==1: # Update  shopcart
                if product.variant == 'None':
                    data = ShopCard.objects.get(product_id=id, user_id=current_user.id)
                else:
                    data = ShopCard.objects.get(product_id=id, variant_id=variantid, user_id=current_user.id)
                data.quantity += form.cleaned_data['quantity']
                data.save()  # save data
            else : # Inser to Shopcart
                data = ShopCard()
                variantid = request.POST.get('variantid')
                data.user_id = current_user.id
                data.product_id =id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)


    else: # if there is no post
        if control == 1:  # Update  shopcart
            data = ShopCard.objects.get(product_id=id, user_id=current_user.id)
            data.quantity += 1
            data.save()  #
        else:  #  Inser to Shopcart
            data = ShopCard()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id =None
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect(url)



    
    # the commented code was for before variant implementation
    # checkproduct = ShopCard.objects.filter(product_id=id) # check product in shop cart
    # if checkproduct:
    #     control = 1 # The product is in the cart
    # else:
    #     control = 0 # the product is not in the cart

    # if request.method == 'POST':
    #     form = ShopCardForm(request.POST)
    #     # although by default we have the name of user, so it should be editable because maybe he/she
    #     # would buy for his relative. so they need to edit the name and address.
    #     if form.is_valid():
    #         if control == 1: # update the shop cart
    #             data = ShopCard.objects.get(product_id=id)
    #             data.quantity += form.cleaned_data['quantity']
    #             data.save()
    #         else: # insert to shop cart
    #             data = ShopCard()
    #             data.user_id = current_user.id 
    #             data.product_id = id 
    #             data.quantity = form.cleaned_data['quantity']
    #             data.save()
    #     messages.success(request, "Product successfully added to cart ")
    #     return HttpResponseRedirect(url)

    # The following else is come form just one product which means that 
    # it only come from home which you can't add many quantity at once
    # else:
    #     if control == 1: # update shopcart 
    #         data = ShopCard.objects.get(product_id = id)
    #         data.quantity += 1 
    #         data.save()
    #     else: # insert to shop cart at the first time
    #         data = ShopCard()
    #         data.user_id = current_user.id 
    #         data.product_id = id 
    #         data.quantity = 1 
    #         data.save()
    #     messages.success(request, "product aded to shop cart")
    #     return HttpResponseRedirect(url)


def shop_card(request):
    category = Category.objects.all()
    shop_card = ShopCard.objects.filter(user_id = request.user.id)
    total = 0 
    for rs in shop_card:
        total += rs.product.price*rs.quantity
    # return HttpResponse(str(total))
    context = {
        'category': category,
        'shop_card': shop_card,
        'total': total
    }

    return render(request, "shop_card_product.html", context)

@login_required
def delete_from_card(request, id):
    ShopCard.objects.filter(id= id).delete()
    messages.success(request, "you have been deleted successfully product item from card")
    return HttpResponseRedirect(reverse('order:shop-card'))


def order_product(request):
    category = Category.objects.all()
    current_user = request.user
    shop_card = ShopCard.objects.filter(user_id=current_user.id)

    total = 0
    for rs in shop_card:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity


    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() #

            # Move shopcart Item to Order product item
            # shop_card = ShopCard.objects.filter(user_id = request.user.id)
            for rs in shop_card:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                if rs.product.variant == 'None':
                    detail.price    = rs.product.price
                else:
                    detail.price = rs.variant.price
                detail.variant_id   = rs.variant_id
                detail.amount        = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product
                if  rs.product.variant=='None':
                    product = Product.objects.get(id=rs.product_id)
                    product.amount -= rs.quantity
                    product.save()
                else:
                    variant = Variants.objects.get(id=rs.product_id)
                    variant.quantity -= rs.quantity
                    variant.save()
                #************ <> *****************

            ShopCard.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'Order_Completed.html',{'ordercode':ordercode,'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    profile = Profile.objects.get(user_id=current_user.id)
    context = {'shop_card': shop_card,
                'category': category,
                'total': total,
                'form': form,
                'profile': profile,
            }
    return render(request, 'Order_Form.html', context)


# def order_product(request):
#     category = Category.objects.all()
#     shop_card = ShopCard.objects.filter(user_id = request.user.id)
#     profile = Profile.objects.get(user_id = request.user.id)
#     total = 0 
#     for rs in shop_card:
#         total += rs.product.price*rs.quantity

#     if request.method == "POST":
#         form = OrderForm(request.POST or None)
#         if form.is_valid():
#             # Here gos to Bank process, Send credit cart to bank and get result of payment info
#             # but here in this project i don't have her 
#             # ................................... bank ............ code ......
#             data = Order()
#             data.first_name = form.cleaned_data['first_name']
#             data.last_name = form.cleaned_data['last_name']
#             data.address = form.cleaned_data['address']
#             data.city = form.cleaned_data['city']
#             data.phone = form.cleaned_data['phone']
#             data.user_id = request.user.id 
#             data.total = total
#             data.ip = request.META.get('REMOTE_ADDR')
#             ordercode = get_random_string(5).upper()
#             data.code = ordercode

order/templates/Order_Completed.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Complated</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/Order_Form.html
{% extends 'homebase.html' %}
{% load currency %}
{% block title %} Order Page {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="{% url 'home:index' %}">Home</a></li>
                <li class="active">Order Page</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div  class="row">
                <Form action="" method="post">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <div class="billing-details">

                            <div class="section-title">
                                <h4 class="title">Shipping Details</h4>
                            </div>
                            <p><label for="id_first_name">First name:</label>
                                <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                            <p><label for="id_last_name">Last name:</label>
                                <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                            <p><label for="id_address">Address:</label>
                                <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                            <p><label for="id_phone">Phone:</label>
                                <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                            <p><label for="id_city">City:</label>
                                <select name="city" class="input" id="id_city">
                                    <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                    <option value="İstanbul">Kabul</option>
                                    <option value="Ankara">Herat</option>
                                    <option value="İzmir">Mazar</option>
                                    <option value="Bursa">Daykundi</option>
                                    <option value="Konya">Badakhshan</option>
                                    <option value="Yozgat">Qandahar</option>
                                </select></p>
                            <p><label for="id_first_name">Country :</label>
                                <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                            <div class="pull-right">
                                <button  type="submit" class="primary-btn">Complete Order</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="shiping-methods">
                            <div class="section-title">
                                <h4 class="title">Payment Information</h4>
                            </div>
                            <p><label for="id_first_name">Total: {{ total|currency:request.session.currency }} {{ request.session.currency }} </label>
                                <input type="text" name="total" class="input" readonly value="{{ total|currency:request.session.currency }} {{ request.session.currency }}"></p>
                            <p><label for="id_first_name">Credit Card Holder</label>
                                <input type="text" name="holder" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Card Number</label>
                                <input type="text" name="number" class="input"  value=""></p>
                            <p><label for="id_first_name">Credit Exp Date/Year</label>
                                <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                            <p><label for="id_first_name">Security Number</label>
                                <input type="text" name="secnumber" class="input"  value=""></p>
                        </div>
                    </div>

                </Form>

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List</h3>
                        </div>
                                                <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Product</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shopcart %}
                                <tr>
                                    <td class="thumb">
                                        {% if rs.variant.image_id  > 0 %}
                                            <img src="{{rs.variant.image }}" alt="">
                                        {% else %}
                                            <img src="{{rs.product.image.url}}" alt="">
                                        {% endif %}

                                    </td>
                                    <td class="details">
                                        <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}</a>  </td>
                                    <td class="price text-center"><strong>
                                        {% if rs.product.variant == 'None' %}
                                            {{ rs.product.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{ rs.variant.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                    </strong></td>
                                    <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>
                                    <td class="total text-center"><strong class="primary-color">$
                                        {% if rs.product.variant == 'None' %}
                                            {{ rs.amount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{ rs.varamount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                    </strong></td>
                                    <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SUBTOTAL</th>
                                <th colspan="2" class="sub-total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SHIPING</th>
                                <td colspan="2">Free Shipping</td>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            </tfoot>
                        </table>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/shop_card_product.html
{% extends 'homebase.html' %}
{% load currency %}
{% block title %} Shop Cart {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Shopcart</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Shopcart Product List</h3>
                        </div>
                        <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th>Image</th>
                                <th>Product</th>
                                <th class="text-center">Price</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Total</th>
                                <th class="text-right"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for rs in shop_card %}
                                <tr>
                                    <td class="thumb">
                                        {% if rs.variant.image_id  > 0 %}
                                            <img src="{{rs.variant.image }}" alt="">
                                        {% else %}
                                            <img src="{{rs.product.image.url}}" alt="">
                                        {% endif %}

                                    </td>
                                    <td class="details">
                                        <a href="{% url 'home:product-detail' rs.product.id rs.product.slug %}">{{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}</a>  </td>
                                    <td class="price text-center"><strong>
                                        {% if rs.product.variant == 'None' %}
                                        {{ rs.product.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{rs.variant.price}}{{ rs.variant.price|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                    </strong></td>
                                    <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>
                                    <td class="total text-center"><strong class="primary-color">$
                                        {% if rs.product.variant == 'None' %}
                                            {{ rs.amount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% else %}
                                            {{ rs.varamount|currency:request.session.currency }} {{ request.session.currency }}
                                        {% endif %}
                                    </strong></td>
                                    <td class="text-right"><a href="{% url 'order:delete-from-card' rs.id %}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                                </tr>

                            {% endfor %}

                            </tbody>
                            <tfoot>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SUBTOTAL</th>
                                <th colspan="2" class="sub-total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>SHIPING</th>
                                <td colspan="2">Free Shipping</td>
                            </tr>
                            <tr>
                                <th class="empty" colspan="3"></th>
                                <th>TOTAL</th>
                                <th colspan="2" class="total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right">
                            <a href="{% url 'order:order-product' %}" class="primary-btn">Place Order</a>
                        </div>
                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}